### ISSUE TITLE
Linx Amender CSS

### ISSUE THREAD

**Issue by MurkBRA** [TimidScript/UserScripts#10]
Hi, first of all, I need to say thank very much! This script is really good. 
I have this little change in my firefox, I change the default text color of black to white and background color of white to black. The table of script have no css color, can you add this css text colors definitions on you script?
![Image with white text color 00](http://i.imgur.com/vWxU4kh.png)
![Image with white text color 01](http://i.imgur.com/38iG4Xx.png)
![Image with white text color 02](http://i.imgur.com/akFybgk.png)

**Comment by TimidScript** [comment]
Hello,
How do you alter the colours like that? 

Test this out: http://pastebin.com/7Es5PaZ1
And let me know if it works. If it does I will update the main script

**Comment by MurkBRA** [comment]
about:preferences#content in fonts and colors you can set any colors to text, background, link and visited link.
Yes, is all fine now.
Thank you.

**Comment by TimidScript** [comment]
Thanks and you are welcome

I just uploaded the latest version. Because you altered the script, GM's automatic update for the script is disabled and you won't get any more auto updates. Through GM, you need to right click it and select update or download it from GreasyFork.
