### ISSUE TITLE
[TS] Linx Amender img bug

### ISSUE THREAD

**Issue by MurkBRA** [TimidScript/UserScripts#11]
Hi, I noticed this bug some days ago but now I see that the cause is linx amender.
All big img that firefox resize got this bug and not show the img on screen.
[Example.](http://starschanges.com/wp-content/uploads/2015/12/Scarlett-Johansson_9.jpg)
I put a exclude with most used formats but is a temp fix.
`// @exclude         /^(.*)(jpg|png|gif|jpeg|bmp|tiff|webp|svg|apng)/`

**Comment by TimidScript** [comment]
I am sorry, I am not sure what I am suppose to be looking at. I can view the image fine. 

LA does not alter the content of the page unless you tell it to. Is there a rule or scripts that edits images? Can you try it on clean profile and see if the issue presists.

**Comment by MurkBRA** [comment]
Ok, seems a combo with [adsbypass](https://adsbypasser.github.io/) bug
To reproduce you need install adsbypass script and try this [link](http://imgsin.com/viewer.php?file=g6spqxv6fddsof3tb8hp.jpg).
Edit: sorry I send the wrong file again, but I edit and fix the link.

**Comment by TimidScript** [comment]
Hi for the first time :),

I installed the full version and it seems to work fine. What exactly do you get? What browser do you have?

**Comment by MurkBRA** [comment]
the image don't show up I'm on firefox 52 64bit

Edit: Sorry I can't reproduce with a clean profile. Close?

**Comment by TimidScript** [comment]
I am unable to reproduce it also. It could be a plugin that is interfering with it. Close if you cannot find the cause, as for obvious reasons I am unable to find it from my end.
