### ISSUE TITLE
pixiv change

### ISSUE THREAD

**Issue by yarrmateys** [TimidScript/UserScripts#13]
when opening works with multiple images, sometimes the bottom button to show thumbnails for all of them doesn't appear anymore. 

http://www.pixiv.net/member_illust.php?mode=medium&illust_id=62213499  for example.

on work listings it looks like trying to open a preview freezes the script, and the light never turns green anymore.

http://www.pixiv.net/member_illust.php?id=23841290

**Comment by Barafag** [comment]
Recent changes broke:
1) iqdb search link
2) original image link

Pixiv announcement:
http://www.pixiv.net/info.php?id=4004

**Comment by Mikachu** [comment]
As a workaround, you can find these two lines,
               metadata.ratings = parseInt(doc.querySelector(".rated-count").textContent);
               metadata.totalRatings = parseInt(doc.querySelector(".score-count").textContent);
(should be 499 and 500) and change to
               metadata.ratings = 0;
               metadata.totalRatings = 0;
and most things should go back to working probably.

**Comment by TimidScript** [comment]
Fixed. Just update and everything should be fine. 
The new like system sucks. I wish there was a permenant start rating system for bookmarks.

**Comment by yarrmateys** [comment]
it works for other people's stuff, but it looks like it doesn't when you try to view your own stuff, both on works page/search and inside.

**Comment by TimidScript** [comment]
They really like to make pointless changes. The old system was better than this like system. 😞 

I will fix when I can.

**Comment by yarrmateys** [comment]
seems like another, bigger change is on the way. pixiv just switched to https, and both this and manga scripts stopped working.

**Comment by TimidScript** [comment]
Should be fixed. Added  a suffix at the end to V3 as currently I have on my system a version 4 alpha which I haven't had the time to finish. 

The other bug in user own page will most likely be fixed in V4 rather than V3.
