### ISSUE TITLE
deviantART Gallery Pager does not work on https sites

### ISSUE THREAD

**Issue by 1n5aN1aC** [TimidScript/UserScripts#2]
I know that deviant-art is not primarily HTTPS, but I force HTTPS on the site, and your script does not work in this case.  I work around this every update by adding the following 2 lines to the comment section:

// @include         http://_.deviantart.com/gallery/_
// @include         http://_.deviantart.com/favourites/_

Alternatively, I think you can remove the http:// part and it'll apply to both?  Not sure though.

**Comment by TimidScript** [comment]
Had I known I would also force it to https. I will include the update in my next release for all dA scripts. 

Thanks

**Comment by 1n5aN1aC** [comment]
Just a comment, I'm not 100% certain on what you meant by "force it to https."

However, if you meant having your script force (redirect) pages to use https, I would recommend against this.

I personally have mine set up to force this, but I would not deploy this to many users, as there are a few minor issues with it on deviantart.  The main one being that it causes animations using flash and similar to not be able to load at all.

So if that's what you meant, I would recommend testing that use case before breaking it for those users who care about that.

As an aside, thanks for making the script.  Makes it soooo much more navigable.

**Comment by TimidScript** [comment]
No, I was going to create a "Linx Amender" (TS:LA) rule, so it automatically redirects to https.

> The main one being that it causes animations using flash and similar to not be able to load at all.

Do you have a sample link? These features won't be in the script, it will be in TS:LA.

**Comment by 1n5aN1aC** [comment]
On additional thought, you may not run into this issue with your TS:LA script on the majority of use cases.

The reason I say this, Is I'm guessing that if you just re-write the page itself to https, I'm guessing it will work, (though I have not tested it) while I just do the browsing with "https everywhere" addon enabled, which will re-write ALL requests to that domain to https requests (including images etc.)

Anyways, here's an example flash on Deviantart that when I browse to the webpage with https everywhere enabled, I don't even get a request to enable flash for this page, because (I honestly don't know what) something is wrong with animations such as this over https on their site:
https://alanbecker.deviantart.com/art/Animator-vs-Animation-34244097

**Comment by TimidScript** [comment]
Fixed flash and converted the embeded illustration images to https. The "Download" button but does not work if you have https. Not sure how videos behave either. But it makes no sense to have https when the embeded content are by default http :?

Anyway, I've not tested this thoroughly but the rule is below if you are interested.  

`{"id":"L1435607263606","name":"deviantArt: iframe source is converted to https","URLs":"^https://(\\w+\\.)?deviantart\\.com/art/","sampleURL":"https://alanbecker.deviantart.com/art/Animator-vs-Animation-34244097","nthNode":"0","type":1,"selectors":"#flashed-in > iframe, .dev-view-deviation img","regexes":[{"name":"src","search":"^http://","replace":"https://"}],"enabled":true,"timestamp":1435607743440}`

**Comment by TimidScript** [comment]
Just let you know I updated the Linx Amender online rules. Now there's a much better support for https in DeviantArt. 

It converts all flashes and images to https. It also converts all internal deviantart links to https so no need for redirection when you are in the site. Currently without the rules the links are all "http" which makes no sense.

**Comment by 1n5aN1aC** [comment]
Looks great!

Though I originally was actually submitting this for the DA autopager to work on HTTPS, and I can't find the commit where you added support for https to the DA autopager.

I totally could have missed it, but when I submitted this, I was actually talking about the DA pager script, though I forgot to mention that. :/  Though your updates to TS:LA update is still great.

**Comment by TimidScript** [comment]
Updated to support https.

<ul><li><a href="https://openuserjs.org/scripts/TimidScript/%5BTS%5D_deviantART_DeviationWatch_Load_All">deviantArt DeviationWatch Load All</a></li>
<li><a href="https://openuserjs.org/scripts/TimidScript/%5BTS%5D_deviantART_Gallery_Pager">deviantArt Gallery &amp; Favourites Auto-Pager</a></li>
<li><a href="https://openuserjs.org/scripts/TimidScript/%5BTS%5D_deviantART_Download_Link">deviantArt Download Link</a></li>
<li><a href="https://openuserjs.org/scripts/TimidScript/%5BTS%5D_deviantART_Friends_List">deviantART Friends List</a></li></ul>

**Comment by 1n5aN1aC** [comment]
Awesome, they all seem to work great!
