### ISSUE TITLE
deviantart.com

### ISSUE THREAD

**Issue by sfilie03** [TimidScript/UserScripts#23]
Hi. The [TS] deviantART Download Link 1.1.20 script doesn't seem to work with Greasemonkey, but does work with Tampermonkey. Is there a way to fix that? Thanks.

Waterfox 56.2.2 (64-bit)
Greasemonkey 4.6
Tampermonkey 4.7.5788
[TS] deviantART Download Link 1.1.20

**Comment by TimidScript** [comment]
Hi,
Short answer is no. GM has changed it's API and broke **ALL** existing scripts (unless they've been updated). It is using a new API.

Your options is to use an alternative Userscript Addon, or go back to GM 3.X and FireFox 56 compatible. I am currently using FF 56 and not updating it. 

FYI: I am on indefinite hiatus from working on the scripts. 

>  Development has been halted till further notice, due to personal issues. Thank you for your understanding.
