### ISSUE TITLE
Pixiv++.user.js: Massive `@icon`...

### ISSUE THREAD

**Issue by Martii** [TimidScript/UserScripts#4]
Seems that [you are currently using](/TimidScript/UserScripts/blob/1c23ee55bf8cfe1f1ea609793c4926f2617e3559/scripts/Pixiv%2B%2B.user.js#L25) a bitmap for your `@icon`... might be good for you and your users to trim this **way** down.

Example:

``` js
// @icon data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAIAAACRXR/mAAACbUlEQVRYw+2YPW/aQBjHj4qormRqPCDLcghiSMCV6vG2ZEkyerCU2Swd+QJ0ruIvQD8AVXZXyggsZfOQwYsDDAghy7JcKRAsxVUZOri4J1o1+OyCVd2z2Tqffve8/s+52oc+yJ69AJk0gkWwCBbBIlipWD6VXUSOLlAH6Jt7d/kYrPaAJXL0ea0Ej1hYKf5xgb0I+kNPNx3L9eNunsMY1YrEN2C5ztEogT0Plt++AwAKLw9Eji5Qvw5sTOdadxQLLh6WIvHNs6rAUOtI+R1jZkwf7EWwsRJW2AY8PD8pRW+07rhjzFLGEhhKk99E8bIXQevWMqYPf//q4qSkyWLkOd10WrdWapWoSPzndxDNId10nmUCAPRGnnpzt1znfhj9dLA0WQxPvMSqLMv1UQ+1Lo+jHMDH0mRRkXgAwDJYqTd3eDXbG3nGdB49Ns+qibAasIwyYdR5ZJ+QZFck/jWVx8fSTScM3HV3nIQpdBiaA2iFxsZ6DFbtwSSsu+STAD2YUKQSdfmOMRMYyp4/JceyF08A/KxleMQCMEk0fK6741TmZqxC3p2CqHMFdJBnBQvNp2eTdUdYsMKiXbQ39DKB1TytooIiE95SJB6dp2HT2TOWyNHvL4/Rdr/NjMdUp9uM23B8tRAm3XS2bDf5BHFh+0OvN/r6u2wXGOqiVlJhGaVvDybtL5Mt98fX8gJDqbCsrvXTveuHcBuKGU80Y2K1B5P+0FMkvs4VwnRGpX3yKwa+tyzXt9aJIjCUUHyViQvZhmNSURn/0WU/VKqRMoEVdv9YsMJqsog8Fj9evf13WDnyA5xgESyCRbAI1q7tB7ebDXxo2NnZAAAAAElFTkSuQmCC
```

Comparison on base64 size here is 13.1 KiB for the bmp versus a mere 474 B _(for the PNG)_... that's **approximately 97% wasted space using a bitmap**.

TIA,
OUJS Admin

---

Ref:
- https://github.com/TimidScript/UserScripts/commit/ab190b02b22ec61d555e996dc6d0a2d793b02a5d

**Comment by TimidScript** [comment]
That's odd, not sure how I used bmp when the files are stored in png.

Thanks, updated the script.

**Comment by TimidScript** [comment]
I know why. I dragged and dropped image from the browser into a converter. The issue exists in a number of my scripts. :)

**Comment by Martii** [comment]
> The issue exists in a number of my scripts

Yes they do! ;) Thanks... don't know if you want this issue closed or not since I "subject"ed it to that particular script.

**Comment by Martii** [comment]
btw unoptimized png but that's minor. ;)

``` sh-session
...
     (16.11% critical chunk reduction)
     (14.42% filesize reduction)
```

**Comment by TimidScript** [comment]
Oh I forget to close issues. I am not use to using this site correctly. 

> btw unoptimized png but that's minor. ;)

I do not have a clue how to optimise it, I just save it as png if it isn't already png :)

**Comment by Martii** [comment]
> I do not have a clue how to optimise it

Don't know if there is a Windows port but I use `$ pngcrush -brute someicon.png someicon.opt.png` to minimize things to their smallest levels. Now you know \~o NBC Public Service theme music\~o

**Comment by TimidScript** [comment]
Yeah that doesn't work. I mainly use an old free version of IcoFx for Windows.

**Comment by Martii** [comment]
Might work in git-bash but I am rarely on Windows. Apparently there is a GUI for it under Windows mentioned [here](http://pmt.sourceforge.net/pngcrush/) if you are interested.

**Comment by Martii** [comment]
Specifically http://trimage.org/

**Comment by TimidScript** [comment]
Thanks for the links. At the moment there's not windows package for it. Made me do a search and found these. 

http://pnggauntlet.com/
http://psydk.org/pngoptimizer

There were the top two. I never really thought about it before.
