### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Martii** [TimidScript/UserScripts#6]
[Re](https://openuserjs.org/scripts/TimidScript/%5BTS%5D_Pixiv++/issues/Pixivv++#comment-15154173793): @TimidScript:   

> NB for myself for future reference

What does the "NB" part stand for? We have a couple of those in the site docs which either need to go away or be expanded and I don't have a clue on your usage yet... one slang site said Nude Beach?!!! ;)

Thanks,
OUJS Admin

**Comment by TimidScript** [comment]
What a coincidence, I earlier looked at the post to update a script for this issue.

NB is latin for "Note Well". Use it mainly in letters just to tell reader to take good notice of the following. In this case notice of the links for possible solution.

**Comment by Martii** [comment]
Pure Latin _(especially abbreviations)_ is probably something the site itself should avoid in the default en-US docs... good to know for future reference and definitely increases my perception when browsing other peoples replies. Thanks for the heads up. :)

**Comment by TimidScript** [comment]
It's commonly used here in the UK. You get taught it very young, when learning to write letters.

**Comment by Martii** [comment]
According to [wikipedia](https://www.wikipedia.org/wiki/Nota_bene) it should include the punctuation. I was taught using **`NOTE:`**, and I usually strong it online. :)

**Comment by TimidScript** [comment]
Yeah it does, I just forgot to add it and there is no edit :)
