### ISSUE TITLE
Linx Amender: Title rules run many times

### ISSUE THREAD

**Issue by igorepst** [TimidScript/UserScripts#7]
Hello, TimidScript. I'm duplicating this bug here, as OpenUserJS is down.
I'm trying to use title rule `@2^(.*): (.*)$` with replacement `$2: Xah Emacs Lisp` for `^http://ergoemacs\.org/emacs/*`, for ex. on [this page](http://ergoemacs.org/emacs/dired_sort.html). The result is that the title is changed for a moment to the right one, and then to "Xah Emacs Lisp: Xah Emacs Lisp". In the console (after adding logging) I see that the function `amendPageTitle(rules)` is called like 4 times. Could you, please, take a look?
Thanks

**Comment by TimidScript** [comment]
Hello, 
np mate. I just replied on OUJS and just saw this afterwards. I could not reproduce this on Windows, so please test it on a clean FF profile. If it still fails, provide a download link to the Linux version you have and I will try to repeat the error in a virtual machine. Not a Linux users, so I hope it is a simple to use version.

**Comment by igorepst** [comment]
Hi,
I can reproduce it with new profile both on [ArchLinux](https://www.archlinux.org/) and with Windows 7 64b. Virtualbox VM. Both have latest FFox
![settings](http://imgur.com/uamjcUSl.png)
![result](http://imgur.com/xbWg1i4l.png)

**Comment by TimidScript** [comment]
Hello,
I really do not know what to say, because I can reproduce it now. I just tested it in LA4 beta and it works fine.

Can you please use this temporary fix. Just copy and paste the rule in LA.

`{"id":"L1459844981456","name":"Emacs","URLs":"@ergoemacs.org","sampleURL":"http://ergoemacs.org/emacs/emacs_org_markup.html","nthNode":"0","type":2,"selectors":"a","regexes":[{"search":"@2^.*: (.*)$","replace":"$1"},{"search":"(.+)","replace":"$1:Xah Emacs Lisp"}],"enabled":true,"timestamp":1460288526565}`

**Comment by igorepst** [comment]
Hello,
The result of pasting this directly is not what I expected 
![result](http://i.imgur.com/QxUsAAZ.png)
:smile:
I really don't want you to spend time on this, as I can wait for LA4. If I have some spare time, perhaps, I'll learn to use Firebug and try to debug this. Thank you, **TimidScript**

**Comment by TimidScript** [comment]
Hi,
 That is embarrassing. Sorry for the half arsed "fix". LA4 has been on almost a year. Every time I get a few hours in, something comes. It's been so long that GIST API has changed and synchronisation and online sharing section is 100% broken. I personally use Linx Amender heavily, and would love to have LA4 finished but stuff happens.

Anyhow, it was a bug. I do not know why it wasn't spotted earlier, as it should get fired a lot. Version 3.0.31 should fix the issue. Let me know if everything is fine (or not).

**Comment by igorepst** [comment]
Seems to be fixed in the latest version. Thanks!
