### ISSUE TITLE
GM_update.js

### ISSUE THREAD

**Issue by Martii** [TimidScript/UserScripts#8]
This library might be going to go away soon on OUJS...

From what I've read you should **not** be scraping script homepages for the versions. I built the meta.json routine just for this as well as you can use the classic meta.js routine.

See how it's used at https://openuserjs.org/about/Frequently-Asked-Questions#q-does-openuserjs-org-have-meta-

TIA,
OUJS Admin

**Comment by TimidScript** [comment]
Thanks for the heads up

I will re-rewrite it to only automatically check meta.js for OUJS and GF, and still continue to support the third party users that use this. Would that be acceptable?

**Comment by Martii** [comment]
> check meta.js for OUJS and GF ... Would that be acceptable?

I can't speak for GF but the /meta route is preferred over scraping any day for OUJS. Unless you absolutely need the .meta.json, which shouldn't be needed for script updating since it should just be a `@version` check, please don't use that over the .meta.js.

TIA,
OUJS Admin

**Comment by TimidScript** [comment]
I will use the meta.js. I have no excuse to use anything else. Not sure why I went another route in the first place.

**Comment by TimidScript** [comment]
Updated the script. 

> Not sure why I went another route in the first place.

It seems the OUJS and the defunct MonkeyGuts did not support meta.js when I first wrote it.

**Comment by Martii** [comment]
[OUJS has always supported .meta.js](https://github.com/OpenUserJs/OpenUserJS.org/commit/de76e3a5f3ebe226f2452a004da1a9b20c010704) ... on dual routes... the /meta route is currently unmanaged ... the /install route is managed and right now I'm clipping TM users to a 503 due to the "Huge Number of Downloads" you posted... e.g. they won't get anything until they update their TM and I release this. I signaled you to come visit that issue btw.

**Comment by TimidScript** [comment]
Then I thought otherwise, because I stated, incorrectly, that it didn't support it in the script guide on initial release.

I just read the thread you linked to. "Why France?" is the only question I have.

**Comment by Martii** [comment]
LOL... good question on that IP... As I stated elsewhere at 3 events happened on April 5th... another possibility is a DDoS attack vector... this is why I've gotten very little sleep... at least it will harden the site with the findings... but it will probably irritate the customers in the meantime.

Sizzle wasn't explicit enough to you when he said we have meta... I knew it but then you ran off and changed things saying we just got it... my bad for not approaching you... but it did result in the FAQ [entry](https://openuserjs.org/about/Frequently-Asked-Questions#q-does-openuserjs-org-have-meta-). :) Just took me some time to build the base.

**Comment by TimidScript** [comment]
I do hope it's not a DDoS attack. 

> probably irritate the customers in the meantime.

I doubt it. If it behaves like USO did towards its end, that would be irritating. Currently, I think everyone understands sites like this go down on occasions. It's not even that bad, on the bright side, I got 100K+ downloads. lol

**Comment by Martii** [comment]
> I got 100K+ downloads. lol

ROFL! ;)

**Comment by Martii** [comment]
You have 200K+ now. ;)

**Comment by TimidScript** [comment]
:D
