### ISSUE TITLE
Licensing conflicts

### ISSUE THREAD

**Issue by Martii** [TimidScript/UserScripts#9]
1. Once GPL always GPL ... GPL is designed to promote FOSS which you keep attempting to close off your source and circumvent.
2. "All Rights Reserved" is incongruous with OSI.
3. You've been demoted back to Author due to these.

If you don't fix item 2 you will be removed... very quickly.

OUJS Admin

---

In lieu of:

[TimidScript](https://github.com/TimidScript) [wrote](https://github.com/TimidScript/UserScripts/issues/9#issuecomment-222169955):

> I can amend any license and utilize it in any way I want.

See also:
- http://www.gnu.org/licenses/gpl-faq.html#WillYouMakeAnException
- http://www.gnu.org/licenses/gpl-faq.html#ModifyGPL

You had years of acknowledging the TOS and years of OSI licensing standards with multiple explanations... so this is why you knew in advance what you were trying to subvert with invalid licensing.

**Comment by Martii** [comment]
Removed.

This will be my final communication with you.

OUJS Admin

**Comment by TimidScript** [comment]
I can amend any license and utilize it in any way I want. It is no longer the same official license but my own personal license. The only thing I broke was OUJS TOS.

Do you really expect anyone to read your message instantaneously? Not only did you remove my scripts but my account (TimidScript and TimidScript2). That's more than just applying the rule, that is vindictive. Do not bother to reply.
